import type { VocabEntry } from '../types';

export const emotionVocab: VocabEntry[] = [
  { display: '寂しさ', reading: 'さびしさ', aliases: ['寂しさ', '寂しい', 'さびしい', 'さみしい'], tags: ['寂', '孤独', '夜'], kind: 'emotion', pos: 'noun' },
  { display: '切なさ', reading: 'せつなさ', aliases: ['切なさ', '切ない', 'せつない'], tags: ['切', '恋', '別れ'], kind: 'emotion', pos: 'noun' },
  { display: 'うれしさ', reading: 'うれしさ', aliases: ['うれしさ', 'うれしい', '嬉しい'], tags: ['喜', '光', '若さ'], kind: 'emotion', pos: 'noun' },
  { display: '悲しみ', reading: 'かなしみ', aliases: ['悲しみ', '悲しい', 'かなしい'], tags: ['悲', '別れ', '雨'], kind: 'emotion', pos: 'noun' },
  { display: '愛しさ', reading: 'いとしさ', aliases: ['愛しさ', '愛しい', 'いとしい'], tags: ['愛', '恋', '人'], kind: 'emotion', pos: 'noun' },
  { display: 'やさしさ', reading: 'やさしさ', aliases: ['やさしさ', 'やさしい', '優しさ', '優しい'], tags: ['優', '関係', '温かさ'], kind: 'emotion', pos: 'noun' },
  { display: 'ときめき', reading: 'ときめき', aliases: ['ときめき', 'ときめく'], tags: ['愛', '高揚', '若さ'], kind: 'emotion', pos: 'noun' },
  { display: '懐かしさ', reading: 'なつかしさ', aliases: ['懐かしさ', '懐かしい', 'なつかしい'], tags: ['懐', '記憶', '時間'], kind: 'emotion', pos: 'noun' },
  { display: '不安', reading: 'ふあん', aliases: ['不安', 'ふあん'], tags: ['不安', '夜', '揺れ'], kind: 'emotion', pos: 'noun' },
  { display: '安堵', reading: 'あんど', aliases: ['安堵', 'あんど', '安心'], tags: ['安心', '部屋', '温かさ'], kind: 'emotion', pos: 'noun' },
  { display: 'ためらい', reading: 'ためらい', aliases: ['ためらい', '躊躇', 'ためらう'], tags: ['迷い', '恋', '沈黙'], kind: 'emotion', pos: 'noun' },
  { display: 'まぶしさ', reading: 'まぶしさ', aliases: ['まぶしさ', '眩しさ', 'まぶしい'], tags: ['光', '若さ', '高揚'], kind: 'emotion', pos: 'noun' },
  { display: 'くやしさ', reading: 'くやしさ', aliases: ['くやしさ', '悔しさ', '悔しい'], tags: ['悔', '熱', '若さ'], kind: 'emotion', pos: 'noun' },
  { display: 'あきらめ', reading: 'あきらめ', aliases: ['あきらめ', '諦め', '諦める'], tags: ['諦', '別れ', '静けさ'], kind: 'emotion', pos: 'noun' },
  { display: '戸惑い', reading: 'とまどい', aliases: ['戸惑い', 'とまどい', '戸惑う'], tags: ['迷い', '関係', '街'], kind: 'emotion', pos: 'noun' },
  { display: 'ぬくもり', reading: 'ぬくもり', aliases: ['ぬくもり', '温もり', '温かい'], tags: ['温かさ', '部屋', '関係'], kind: 'emotion', pos: 'noun' },
  { display: '孤独', reading: 'こどく', aliases: ['孤独', 'こどく', 'ひとり'], tags: ['孤独', '夜', '静けさ'], kind: 'emotion', pos: 'noun' },
  { display: '希望', reading: 'きぼう', aliases: ['希望', 'きぼう'], tags: ['希望', '光', '朝'], kind: 'emotion', pos: 'noun' },
  { display: '後悔', reading: 'こうかい', aliases: ['後悔', 'こうかい', '悔いる'], tags: ['悔', '記憶', '時間'], kind: 'emotion', pos: 'noun' },
  { display: 'ため息', reading: 'ためいき', aliases: ['ため息', '溜息', 'ためいき'], tags: ['疲れ', '夜', '沈黙'], kind: 'emotion', pos: 'noun' },
  { display: '恋しさ', reading: 'こいしさ', aliases: ['恋しさ', '恋しい', 'こいしい'], tags: ['恋', '愛', '距離'], kind: 'emotion', pos: 'noun' },
  { display: '痛み', reading: 'いたみ', aliases: ['痛み', '痛い', 'いたい'], tags: ['痛', '別れ', '身体'], kind: 'emotion', pos: 'noun' },
  { display: '迷い', reading: 'まよい', aliases: ['迷い', '迷う', 'まよう'], tags: ['迷い', '道', '関係'], kind: 'emotion', pos: 'noun' },
  { display: 'しずけさ', reading: 'しずけさ', aliases: ['静けさ', 'しずけさ', '静か'], tags: ['静けさ', '夜', '部屋'], kind: 'emotion', pos: 'noun' },
  { display: '高鳴り', reading: 'たかなり', aliases: ['高鳴り', 'たかなり', '高鳴る'], tags: ['高揚', '恋', '胸'], kind: 'emotion', pos: 'noun' },
  { display: 'あたたかさ', reading: 'あたたかさ', aliases: ['温かさ', 'あたたかさ', 'あたたかい'], tags: ['温かさ', '安心', '部屋'], kind: 'emotion', pos: 'noun' },
  // --- 拡充 (4 モーラ) ---
  { display: 'むなしさ', reading: 'むなしさ', aliases: ['むなしさ', '虚しさ', '空しい'], tags: ['寂', '虚', '夜'], kind: 'emotion', pos: 'noun' },
  { display: 'ものうさ', reading: 'ものうさ', aliases: ['ものうさ', '物憂さ', '物憂い'], tags: ['倦怠', '夏', '昼'], kind: 'emotion', pos: 'noun' },
  { display: 'けだるさ', reading: 'けだるさ', aliases: ['けだるさ', '気怠さ', '気だるい'], tags: ['倦怠', '夏', '昼'], kind: 'emotion', pos: 'noun' },
  { display: 'うらやみ', reading: 'うらやみ', aliases: ['うらやみ', '羨み', '羨ましい'], tags: ['羨', '関係', '街'], kind: 'emotion', pos: 'noun' },
  { display: 'たのしさ', reading: 'たのしさ', aliases: ['たのしさ', '楽しさ', '楽しい'], tags: ['喜', '若さ', '光'], kind: 'emotion', pos: 'noun' },
  { display: 'やすらぎ', reading: 'やすらぎ', aliases: ['やすらぎ', '安らぎ', '安らか'], tags: ['安心', '温かさ', '部屋'], kind: 'emotion', pos: 'noun' },
  { display: '幸福', reading: 'こうふく', aliases: ['幸福', 'こうふく', '幸せ', 'しあわせ'], tags: ['喜', '安心', '光'], kind: 'emotion', pos: 'noun' },
  { display: '憂鬱', reading: 'ゆううつ', aliases: ['憂鬱', 'ゆううつ', '憂うつ'], tags: ['悲', '不安', '雨'], kind: 'emotion', pos: 'noun' },
  { display: 'あこがれ', reading: 'あこがれ', aliases: ['あこがれ', '憧れ', '憧れる'], tags: ['愛', '恋', '光'], kind: 'emotion', pos: 'noun' },
  { display: '思い出', reading: 'おもいで', aliases: ['思い出', 'おもいで', '想い出'], tags: ['懐', '記憶', '時間'], kind: 'emotion', pos: 'noun' },
  { display: '青春', reading: 'せいしゅん', aliases: ['青春', 'せいしゅん'], tags: ['懐', '若さ', '記憶'], kind: 'emotion', pos: 'noun' },
];
