import type { VocabEntry } from '../types';

export const motifVocab: VocabEntry[] = [
  { display: 'コンビニ', reading: 'こんびに', aliases: ['コンビニ', 'こんびに', 'セブン', 'ローソン', 'ファミマ'], tags: ['街', '日常', '灯', '場面'], kind: 'motif', pos: 'noun' },
  { display: 'コーヒー', reading: 'こーひー', aliases: ['コーヒー', 'こーひー', '珈琲'], tags: ['飲み物', '日常', '苦味'], kind: 'motif', pos: 'noun' },
  { display: '街灯', reading: 'がいとう', aliases: ['街灯', 'がいとう'], tags: ['街', '夜', '光', '場面'], kind: 'motif', pos: 'noun' },
  { display: '約束', reading: 'やくそく', aliases: ['約束', 'やくそく'], tags: ['関係', '時間', '人'], kind: 'motif', pos: 'noun' },
  { display: '電車', reading: 'でんしゃ', aliases: ['電車', 'でんしゃ'], tags: ['街', '移動', '音', '場面'], kind: 'motif', pos: 'noun' },
  { display: '写真', reading: 'しゃしん', aliases: ['写真', 'しゃしん'], tags: ['記憶', '過去', '静物'], kind: 'motif', pos: 'noun' },
  { display: '真昼', reading: 'まひる', aliases: ['真昼', 'まひる', '昼'], tags: ['時間', '光', '日中', '場面'], kind: 'motif', pos: 'noun' },
  { display: '駅', reading: 'えき', aliases: ['駅', 'えき'], tags: ['街', '移動', '別れ', '場面'], kind: 'motif', pos: 'noun' },
  { display: '海', reading: 'うみ', aliases: ['海', 'うみ'], tags: ['自然', '青', '遠さ', '場面'], kind: 'motif', pos: 'noun' },
  { display: '君', reading: 'きみ', aliases: ['君', 'きみ', 'あなた', 'あの人'], tags: ['人', '関係', '恋'], kind: 'motif', pos: 'noun' },
  { display: '友だち', reading: 'ともだち', aliases: ['友だち', '友達', 'ともだち'], tags: ['人', '関係', '日常'], kind: 'motif', pos: 'noun' },
  { display: '母', reading: 'はは', aliases: ['母', 'お母さん', 'はは'], tags: ['人', '家族', '部屋'], kind: 'motif', pos: 'noun' },
  { display: 'あなた', reading: 'あなた', aliases: ['あなた', '君', 'きみ'], tags: ['人', '関係', '恋'], kind: 'motif', pos: 'noun' },
  { display: 'わたし', reading: 'わたし', aliases: ['私', 'わたし', '自分'], tags: ['人', '自分', '内面'], kind: 'motif', pos: 'noun' },
  { display: '誰か', reading: 'だれか', aliases: ['誰か', 'だれか'], tags: ['人', '曖昧', '関係'], kind: 'motif', pos: 'noun' },
  { display: '返信', reading: 'へんしん', aliases: ['返信', 'へんしん', '返事'], tags: ['関係', 'スマホ', '待つ'], kind: 'motif', pos: 'noun' },
  { display: 'スマホ', reading: 'すまほ', aliases: ['スマホ', '携帯', 'すまほ'], tags: ['街', '日常', '光', '場面'], kind: 'motif', pos: 'noun' },
  { display: '改札', reading: 'かいさつ', aliases: ['改札', 'かいさつ'], tags: ['街', '移動', '別れ', '場面'], kind: 'motif', pos: 'noun' },
  { display: 'ベランダ', reading: 'べらんだ', aliases: ['ベランダ', 'べらんだ'], tags: ['部屋', '空', '日常', '場面'], kind: 'motif', pos: 'noun' },
  { display: '台所', reading: 'だいどこ', aliases: ['台所', 'キッチン', 'だいどこ'], tags: ['部屋', '食べ物', '家族', '場面'], kind: 'motif', pos: 'noun' },
  { display: '制服', reading: 'せいふく', aliases: ['制服', 'せいふく'], tags: ['若さ', '学校', '記憶'], kind: 'motif', pos: 'noun' },
  { display: 'ノート', reading: 'のーと', aliases: ['ノート', 'のーと'], tags: ['学校', '記憶', '紙'], kind: 'motif', pos: 'noun' },
  { display: '手紙', reading: 'てがみ', aliases: ['手紙', 'てがみ'], tags: ['関係', '紙', '記憶'], kind: 'motif', pos: 'noun' },
  { display: '指先', reading: 'ゆびさき', aliases: ['指先', 'ゆびさき'], tags: ['身体', '人', '触れる'], kind: 'motif', pos: 'noun' },
  { display: '靴音', reading: 'くつおと', aliases: ['靴音', 'くつおと'], tags: ['街', '音', '移動'], kind: 'motif', pos: 'noun' },
  { display: '窓', reading: 'まど', aliases: ['窓', 'まど'], tags: ['部屋', '光', '境界', '場面'], kind: 'motif', pos: 'noun' },
  { display: '空', reading: 'そら', aliases: ['空', 'そら'], tags: ['自然', '遠さ', '光', '場面'], kind: 'motif', pos: 'noun' },
  { display: '橋', reading: 'はし', aliases: ['橋', 'はし'], tags: ['街', '境界', '移動', '場面'], kind: 'motif', pos: 'noun' },
  { display: '雨傘', reading: 'あまがさ', aliases: ['雨傘', '傘', 'あまがさ'], tags: ['雨', '街', '持ち物'], kind: 'motif', pos: 'noun' },
  { display: '卵焼き', reading: 'たまごやき', aliases: ['卵焼き', '玉子焼き', 'たまごやき'], tags: ['食べ物', '部屋', '家族'], kind: 'motif', pos: 'noun' },
  { display: '味噌汁', reading: 'みそしる', aliases: ['味噌汁', 'みそ汁', 'みそしる'], tags: ['食べ物', '朝', '家族'], kind: 'motif', pos: 'noun' },
  { display: '夜道', reading: 'よみち', aliases: ['夜道', 'よみち'], tags: ['夜', '街', '孤独', '場面'], kind: 'motif', pos: 'noun' },
  // --- 拡充: 人 (3 モーラ) ---
  { display: '彼女', reading: 'かのじょ', aliases: ['彼女', 'かのじょ'], tags: ['人', '関係', '恋'], kind: 'motif', pos: 'noun' },
  { display: 'あの子', reading: 'あのこ', aliases: ['あの子', 'あのこ'], tags: ['人', '関係', '恋'], kind: 'motif', pos: 'noun' },
  { display: 'ふたり', reading: 'ふたり', aliases: ['ふたり', '二人'], tags: ['人', '関係', '恋'], kind: 'motif', pos: 'noun' },
  { display: 'ひとり', reading: 'ひとり', aliases: ['ひとり', '独り', '一人'], tags: ['人', '自分', '孤独'], kind: 'motif', pos: 'noun' },
  { display: '仲間', reading: 'なかま', aliases: ['仲間', 'なかま'], tags: ['人', '関係', '日常'], kind: 'motif', pos: 'noun' },
  { display: '子ども', reading: 'こども', aliases: ['子ども', '子供', 'こども'], tags: ['人', '家族', '日常'], kind: 'motif', pos: 'noun' },
  { display: '家族', reading: 'かぞく', aliases: ['家族', 'かぞく'], tags: ['人', '家族', '部屋'], kind: 'motif', pos: 'noun' },
  // --- 拡充: 人 (2 モーラ) ---
  { display: '彼', reading: 'かれ', aliases: ['彼', 'かれ'], tags: ['人', '関係', '恋'], kind: 'motif', pos: 'noun' },
  { display: '父', reading: 'ちち', aliases: ['父', 'お父さん', 'ちち'], tags: ['人', '家族', '部屋'], kind: 'motif', pos: 'noun' },
  { display: '友', reading: 'とも', aliases: ['友', 'とも'], tags: ['人', '関係', '日常'], kind: 'motif', pos: 'noun' },
  // --- 拡充: 場面 (3 モーラ) ---
  { display: '窓辺', reading: 'まどべ', aliases: ['窓辺', 'まどべ'], tags: ['部屋', '光', '境界', '場面'], kind: 'motif', pos: 'noun' },
  { display: 'ホーム', reading: 'ほーむ', aliases: ['ホーム', 'ほーむ'], tags: ['街', '移動', '別れ', '場面'], kind: 'motif', pos: 'noun' },
  { display: '夜明け', reading: 'よあけ', aliases: ['夜明け', 'よあけ'], tags: ['朝', '光', '時間', '場面'], kind: 'motif', pos: 'noun' },
  { display: '港', reading: 'みなと', aliases: ['港', 'みなと'], tags: ['街', '海', '遠さ', '場面'], kind: 'motif', pos: 'noun' },
  { display: '通り', reading: 'とおり', aliases: ['通り', 'とおり'], tags: ['街', '移動', '場面'], kind: 'motif', pos: 'noun' },
  { display: '喫茶', reading: 'きっさ', aliases: ['喫茶', 'きっさ', '喫茶店'], tags: ['街', '日常', '場面'], kind: 'motif', pos: 'noun' },
  // --- 拡充: 物・自然 (2 モーラ, !人) ---
  { display: '道', reading: 'みち', aliases: ['道', 'みち'], tags: ['街', '移動', '場面'], kind: 'motif', pos: 'noun' },
  { display: '壁', reading: 'かべ', aliases: ['壁', 'かべ'], tags: ['部屋', '境界'], kind: 'motif', pos: 'noun' },
  { display: '鳥', reading: 'とり', aliases: ['鳥', 'とり'], tags: ['自然', '空', '移動'], kind: 'motif', pos: 'noun' },
  { display: '夢', reading: 'ゆめ', aliases: ['夢', 'ゆめ'], tags: ['夜', '記憶', '内面'], kind: 'motif', pos: 'noun' },
  { display: '波', reading: 'なみ', aliases: ['波', 'なみ'], tags: ['自然', '海', '揺れ'], kind: 'motif', pos: 'noun' },
  { display: '声', reading: 'こえ', aliases: ['声', 'こえ'], tags: ['音', '関係', '記憶'], kind: 'motif', pos: 'noun' },
  // --- 拡充: 物・身体 (3 モーラ, !人) ---
  { display: '机', reading: 'つくえ', aliases: ['机', 'つくえ'], tags: ['部屋', '学校', '静物'], kind: 'motif', pos: 'noun' },
  { display: '鞄', reading: 'かばん', aliases: ['鞄', 'かばん', 'カバン'], tags: ['持ち物', '移動', '街'], kind: 'motif', pos: 'noun' },
  { display: '言葉', reading: 'ことば', aliases: ['言葉', 'ことば'], tags: ['関係', '記憶', '内面'], kind: 'motif', pos: 'noun' },
  { display: '涙', reading: 'なみだ', aliases: ['涙', 'なみだ'], tags: ['身体', '悲', '雨'], kind: 'motif', pos: 'noun' },
  { display: '笑顔', reading: 'えがお', aliases: ['笑顔', 'えがお'], tags: ['身体', '喜', '光'], kind: 'motif', pos: 'noun' },
  { display: '枕', reading: 'まくら', aliases: ['枕', 'まくら'], tags: ['部屋', '夜', '静物'], kind: 'motif', pos: 'noun' },
  { display: '指輪', reading: 'ゆびわ', aliases: ['指輪', 'ゆびわ'], tags: ['持ち物', '恋', '関係'], kind: 'motif', pos: 'noun' },
  { display: '氷', reading: 'こおり', aliases: ['氷', 'こおり'], tags: ['冬', '水', '静物'], kind: 'motif', pos: 'noun' },
  { display: '光', reading: 'ひかり', aliases: ['光', 'ひかり'], tags: ['光', '自然', '希望'], kind: 'motif', pos: 'noun' },
];
