import type { VocabEntry } from '../types';

export const seasonVocab: VocabEntry[] = [
  { display: '春風', reading: 'はるかぜ', aliases: ['春風', 'はるかぜ', '春の風'], tags: ['春', '風', '若さ'], kind: 'season', pos: 'noun' },
  { display: '春雨', reading: 'はるさめ', aliases: ['春雨', 'はるさめ'], tags: ['春', '雨', '静けさ'], kind: 'season', pos: 'noun' },
  { display: '花冷え', reading: 'はなびえ', aliases: ['花冷え', 'はなびえ'], tags: ['春', '花', '寒さ'], kind: 'season', pos: 'noun' },
  { display: '桜', reading: 'さくら', aliases: ['桜', 'さくら', 'サクラ'], tags: ['春', '花', '別れ'], kind: 'season', pos: 'noun' },
  { display: '霞', reading: 'かすみ', aliases: ['霞', 'かすみ'], tags: ['春', '空', '曖昧'], kind: 'season', pos: 'noun' },
  { display: '若葉', reading: 'わかば', aliases: ['若葉', 'わかば'], tags: ['春', '緑', '若さ'], kind: 'season', pos: 'noun' },
  { display: '菜の花', reading: 'なのはな', aliases: ['菜の花', 'なのはな'], tags: ['春', '花', '黄色'], kind: 'season', pos: 'noun' },
  { display: 'つばめ', reading: 'つばめ', aliases: ['燕', 'つばめ'], tags: ['春', '鳥', '移動'], kind: 'season', pos: 'noun' },
  { display: '夕立', reading: 'ゆうだち', aliases: ['夕立', 'ゆうだち', '夕立ち'], tags: ['夏', '雨', '街'], kind: 'season', pos: 'noun' },
  { display: '朝顔', reading: 'あさがお', aliases: ['朝顔', 'あさがお'], tags: ['夏', '花', '朝'], kind: 'season', pos: 'noun' },
  { display: '蝉', reading: 'せみ', aliases: ['蝉', 'せみ', 'セミ'], tags: ['夏', '声', '暑さ'], kind: 'season', pos: 'noun' },
  { display: '麦茶', reading: 'むぎちゃ', aliases: ['麦茶', 'むぎちゃ'], tags: ['夏', '飲み物', '日常'], kind: 'season', pos: 'noun' },
  { display: '夏雲', reading: 'なつぐも', aliases: ['夏雲', 'なつぐも'], tags: ['夏', '空', '白'], kind: 'season', pos: 'noun' },
  { display: '夕焼け', reading: 'ゆうやけ', aliases: ['夕焼け', '夕焼', 'ゆうやけ'], tags: ['夏', '夕方', '空'], kind: 'season', pos: 'noun' },
  { display: '風鈴', reading: 'ふうりん', aliases: ['風鈴', 'ふうりん'], tags: ['夏', '音', '風'], kind: 'season', pos: 'noun' },
  { display: '青嵐', reading: 'あおあらし', aliases: ['青嵐', 'あおあらし'], tags: ['夏', '風', '緑'], kind: 'season', pos: 'noun' },
  { display: '朝霧', reading: 'あさぎり', aliases: ['朝霧', 'あさぎり'], tags: ['秋', '霧', '朝'], kind: 'season', pos: 'noun' },
  { display: '落葉', reading: 'おちば', aliases: ['落葉', '落ち葉', 'おちば'], tags: ['秋', '葉', '別れ'], kind: 'season', pos: 'noun' },
  { display: '月', reading: 'つき', aliases: ['月', 'つき'], tags: ['秋', '夜空', '孤独'], kind: 'season', pos: 'noun' },
  { display: '秋雨', reading: 'あきさめ', aliases: ['秋雨', 'あきさめ'], tags: ['秋', '雨', '静けさ'], kind: 'season', pos: 'noun' },
  { display: '金木犀', reading: 'きんもくせい', aliases: ['金木犀', 'きんもくせい'], tags: ['秋', '香り', '記憶'], kind: 'season', pos: 'noun' },
  { display: '鰯雲', reading: 'いわしぐも', aliases: ['鰯雲', 'いわしぐも'], tags: ['秋', '空', '遠さ'], kind: 'season', pos: 'noun' },
  { display: '虫の音', reading: 'むしのね', aliases: ['虫の音', '虫の声', 'むしのね'], tags: ['秋', '音', '夜'], kind: 'season', pos: 'noun' },
  { display: '柿', reading: 'かき', aliases: ['柿', 'かき'], tags: ['秋', '食べ物', '橙'], kind: 'season', pos: 'noun' },
  { display: '北風', reading: 'きたかぜ', aliases: ['北風', 'きたかぜ'], tags: ['冬', '風', '寒さ'], kind: 'season', pos: 'noun' },
  { display: '雪', reading: 'ゆき', aliases: ['雪', 'ゆき'], tags: ['冬', '白', '静けさ'], kind: 'season', pos: 'noun' },
  { display: '冬空', reading: 'ふゆぞら', aliases: ['冬空', 'ふゆぞら'], tags: ['冬', '空', '寒さ'], kind: 'season', pos: 'noun' },
  { display: '霜柱', reading: 'しもばしら', aliases: ['霜柱', 'しもばしら'], tags: ['冬', '朝', '白'], kind: 'season', pos: 'noun' },
  { display: '白息', reading: 'しらいき', aliases: ['白息', '白い息', 'しらいき'], tags: ['冬', '息', '寒さ'], kind: 'season', pos: 'noun' },
  { display: '冬晴れ', reading: 'ふゆばれ', aliases: ['冬晴れ', 'ふゆばれ'], tags: ['冬', '空', '光'], kind: 'season', pos: 'noun' },
  { display: 'こたつ', reading: 'こたつ', aliases: ['こたつ', '炬燵'], tags: ['冬', '部屋', '日常'], kind: 'season', pos: 'noun' },
  { display: '湯気', reading: 'ゆげ', aliases: ['湯気', 'ゆげ'], tags: ['冬', '食べ物', '温かさ'], kind: 'season', pos: 'noun' },
];
