import type { VocabEntry } from '../types';

/**
 * 動詞は活用済みの形を個別エントリで持つ。 tags で意味制約をかける。
 */
export const verbsVocab: VocabEntry[] = [
  { display: '待つ', reading: 'まつ', aliases: ['待つ', 'まつ'], tags: ['動作', '人', '待つ', '他動'], kind: 'verb', pos: 'verb-終止' },
  { display: '待って', reading: 'まって', aliases: ['待って', 'まって'], tags: ['動作', '人', '待つ', '他動'], kind: 'verb', pos: 'verb-テ' },
  { display: '笑う', reading: 'わらう', aliases: ['笑う', 'わらう'], tags: ['心情', '人'], kind: 'verb', pos: 'verb-終止' },
  { display: '笑って', reading: 'わらって', aliases: ['笑って', 'わらって'], tags: ['心情', '人'], kind: 'verb', pos: 'verb-テ' },
  { display: '泣く', reading: 'なく', aliases: ['泣く', 'なく'], tags: ['心情', '人'], kind: 'verb', pos: 'verb-終止' },
  { display: '泣いて', reading: 'ないて', aliases: ['泣いて', 'ないて'], tags: ['心情', '人'], kind: 'verb', pos: 'verb-テ' },
  { display: '見る', reading: 'みる', aliases: ['見る', 'みる'], tags: ['動作', '人', '他動'], kind: 'verb', pos: 'verb-終止' },
  { display: '見て', reading: 'みて', aliases: ['見て', 'みて'], tags: ['動作', '人', '他動'], kind: 'verb', pos: 'verb-テ' },
  { display: '見つめる', reading: 'みつめる', aliases: ['見つめる', 'みつめる'], tags: ['動作', '人', '他動'], kind: 'verb', pos: 'verb-終止' },
  { display: '見つめて', reading: 'みつめて', aliases: ['見つめて', 'みつめて'], tags: ['動作', '人', '他動'], kind: 'verb', pos: 'verb-テ' },
  { display: '思う', reading: 'おもう', aliases: ['思う', 'おもう'], tags: ['心情', '人'], kind: 'verb', pos: 'verb-終止' },
  { display: '思って', reading: 'おもって', aliases: ['思って', 'おもって'], tags: ['心情', '人'], kind: 'verb', pos: 'verb-テ' },
  { display: '帰る', reading: 'かえる', aliases: ['帰る', 'かえる'], tags: ['動作', '人', '移動'], kind: 'verb', pos: 'verb-終止' },
  { display: '帰って', reading: 'かえって', aliases: ['帰って', 'かえって'], tags: ['動作', '人', '移動'], kind: 'verb', pos: 'verb-テ' },
  { display: '飲む', reading: 'のむ', aliases: ['飲む', 'のむ'], tags: ['動作', '人', '他動'], kind: 'verb', pos: 'verb-終止' },
  { display: '飲んで', reading: 'のんで', aliases: ['飲んで', 'のんで'], tags: ['動作', '人', '他動'], kind: 'verb', pos: 'verb-テ' },
  { display: '歩く', reading: 'あるく', aliases: ['歩く', 'あるく'], tags: ['動作', '人', '移動'], kind: 'verb', pos: 'verb-終止' },
  { display: '歩いて', reading: 'あるいて', aliases: ['歩いて', 'あるいて'], tags: ['動作', '人', '移動'], kind: 'verb', pos: 'verb-テ' },
  { display: '走る', reading: 'はしる', aliases: ['走る', 'はしる'], tags: ['動作', '移動'], kind: 'verb', pos: 'verb-終止' },
  { display: '走って', reading: 'はしって', aliases: ['走って', 'はしって'], tags: ['動作', '移動'], kind: 'verb', pos: 'verb-テ' },
  { display: '光る', reading: 'ひかる', aliases: ['光る', 'ひかる'], tags: ['自然', '光', '非人'], kind: 'verb', pos: 'verb-終止' },
  { display: '光って', reading: 'ひかって', aliases: ['光って', 'ひかって'], tags: ['自然', '光', '非人'], kind: 'verb', pos: 'verb-テ' },
  { display: '残る', reading: 'のこる', aliases: ['残る', 'のこる'], tags: ['存在', '記憶', '非人'], kind: 'verb', pos: 'verb-終止' },
  { display: '残って', reading: 'のこって', aliases: ['残って', 'のこって'], tags: ['存在', '記憶', '非人'], kind: 'verb', pos: 'verb-テ' },
  { display: '消える', reading: 'きえる', aliases: ['消える', 'きえる'], tags: ['変化', '非人'], kind: 'verb', pos: 'verb-終止' },
  { display: '消えて', reading: 'きえて', aliases: ['消えて', 'きえて'], tags: ['変化', '非人'], kind: 'verb', pos: 'verb-テ' },
  { display: '揺れる', reading: 'ゆれる', aliases: ['揺れる', 'ゆれる'], tags: ['自然', '揺れ', '非人'], kind: 'verb', pos: 'verb-終止' },
  { display: '揺れて', reading: 'ゆれて', aliases: ['揺れて', 'ゆれて'], tags: ['自然', '揺れ', '非人'], kind: 'verb', pos: 'verb-テ' },
  { display: '響く', reading: 'ひびく', aliases: ['響く', 'ひびく'], tags: ['音', '非人'], kind: 'verb', pos: 'verb-終止' },
  { display: '響いて', reading: 'ひびいて', aliases: ['響いて', 'ひびいて'], tags: ['音', '非人'], kind: 'verb', pos: 'verb-テ' },
  { display: '滲む', reading: 'にじむ', aliases: ['滲む', 'にじむ'], tags: ['変化', '雨', '非人'], kind: 'verb', pos: 'verb-終止' },
  { display: '滲んで', reading: 'にじんで', aliases: ['滲んで', 'にじんで'], tags: ['変化', '雨', '非人'], kind: 'verb', pos: 'verb-テ' },
  { display: '灯る', reading: 'ともる', aliases: ['灯る', 'ともる'], tags: ['光', '街', '非人'], kind: 'verb', pos: 'verb-終止' },
  { display: '灯って', reading: 'ともって', aliases: ['灯って', 'ともって'], tags: ['光', '街', '非人'], kind: 'verb', pos: 'verb-テ' },
  { display: 'ほどける', reading: 'ほどける', aliases: ['ほどける', '解ける'], tags: ['変化', '関係', '非人'], kind: 'verb', pos: 'verb-終止' },
  { display: 'ほどけて', reading: 'ほどけて', aliases: ['ほどけて', '解けて'], tags: ['変化', '関係', '非人'], kind: 'verb', pos: 'verb-テ' },
  { display: '満ちる', reading: 'みちる', aliases: ['満ちる', 'みちる'], tags: ['存在', '光', '非人'], kind: 'verb', pos: 'verb-終止' },
  { display: '満ちて', reading: 'みちて', aliases: ['満ちて', 'みちて'], tags: ['存在', '光', '非人'], kind: 'verb', pos: 'verb-テ' },
  { display: '覚める', reading: 'さめる', aliases: ['覚める', 'さめる'], tags: ['変化', '朝'], kind: 'verb', pos: 'verb-終止' },
  { display: '覚めて', reading: 'さめて', aliases: ['覚めて', 'さめて'], tags: ['変化', '朝'], kind: 'verb', pos: 'verb-テ' },
  { display: '眠る', reading: 'ねむる', aliases: ['眠る', 'ねむる'], tags: ['動作', '人', '夜'], kind: 'verb', pos: 'verb-終止' },
  { display: '眠って', reading: 'ねむって', aliases: ['眠って', 'ねむって'], tags: ['動作', '人', '夜'], kind: 'verb', pos: 'verb-テ' },
  { display: '呼ぶ', reading: 'よぶ', aliases: ['呼ぶ', 'よぶ'], tags: ['動作', '人', '他動'], kind: 'verb', pos: 'verb-終止' },
  { display: '呼んで', reading: 'よんで', aliases: ['呼んで', 'よんで'], tags: ['動作', '人', '他動'], kind: 'verb', pos: 'verb-テ' },
  { display: '触れる', reading: 'ふれる', aliases: ['触れる', 'ふれる'], tags: ['動作', '人', '他動'], kind: 'verb', pos: 'verb-終止' },
  { display: '触れて', reading: 'ふれて', aliases: ['触れて', 'ふれて'], tags: ['動作', '人', '他動'], kind: 'verb', pos: 'verb-テ' },
  { display: '拾う', reading: 'ひろう', aliases: ['拾う', 'ひろう'], tags: ['動作', '人', '他動'], kind: 'verb', pos: 'verb-終止' },
  { display: '拾って', reading: 'ひろって', aliases: ['拾って', 'ひろって'], tags: ['動作', '人', '他動'], kind: 'verb', pos: 'verb-テ' },
  { display: '選ぶ', reading: 'えらぶ', aliases: ['選ぶ', 'えらぶ'], tags: ['動作', '人', '他動'], kind: 'verb', pos: 'verb-終止' },
  { display: '選んで', reading: 'えらんで', aliases: ['選んで', 'えらんで'], tags: ['動作', '人', '他動'], kind: 'verb', pos: 'verb-テ' },
  { display: '染まる', reading: 'そまる', aliases: ['染まる', 'そまる'], tags: ['変化', '色', '非人'], kind: 'verb', pos: 'verb-終止' },
  { display: '染まって', reading: 'そまって', aliases: ['染まって', 'そまって'], tags: ['変化', '色', '非人'], kind: 'verb', pos: 'verb-テ' },
  { display: 'ほどく', reading: 'ほどく', aliases: ['ほどく', '解く'], tags: ['動作', '人', '他動'], kind: 'verb', pos: 'verb-終止' },
  { display: 'ほどいて', reading: 'ほどいて', aliases: ['ほどいて', '解いて'], tags: ['動作', '人', '他動'], kind: 'verb', pos: 'verb-テ' },
  { display: '広がる', reading: 'ひろがる', aliases: ['広がる', 'ひろがる'], tags: ['変化', '空', '非人'], kind: 'verb', pos: 'verb-終止' },
  { display: '静まる', reading: 'しずまる', aliases: ['静まる', 'しずまる'], tags: ['変化', '静けさ', '非人'], kind: 'verb', pos: 'verb-終止' },
  { display: '震える', reading: 'ふるえる', aliases: ['震える', 'ふるえる'], tags: ['揺れ', '寒さ', '非人'], kind: 'verb', pos: 'verb-終止' },
  { display: '流れる', reading: 'ながれる', aliases: ['流れる', 'ながれる'], tags: ['変化', '時間', '非人'], kind: 'verb', pos: 'verb-終止' },
  { display: '輝く', reading: 'かがやく', aliases: ['輝く', 'かがやく'], tags: ['光', '非人'], kind: 'verb', pos: 'verb-終止' },
  { display: 'かすれる', reading: 'かすれる', aliases: ['かすれる', '掠れる'], tags: ['音', '記憶', '非人'], kind: 'verb', pos: 'verb-終止' },
  { display: '笑む', reading: 'えむ', aliases: ['笑む', 'ほほえむ'], tags: ['心情', '人'], kind: 'verb', pos: 'verb-終止' },
];
